Сверстала адаптивную сетку для внутренних страниц
htmlacademy-adaptive/1899553-mishka-25 pull request #5
Opened 2022-04-28 12:34 UTC by kuznetsovaleksandra

2022-04-29 10:50 UTC, craz3r requested changes
1. Удалить конструкции `background-image: url("");` т.к в итоге на странице это превращается в `background-image: url(style.css);` что по сути не имеет смысла

2. Разобраться с использованием значений внутри media выражений, тк сейчас где то используются переменные, а где то конкретные значения. Нужно привести к одному виду (желательно использовать переменные)

2022-04-29 10:50 UTC, craz3r commented on source/sass/blocks/catalog.scss
> +  background-image: url("");
Пустой background-image? может удалить тогда?

2022-05-02 12:03 UTC, kuznetsovaleksandra commented
> 1. Удалить конструкции `background-image: url("");` т.к в итоге на странице это превращается в `background-image: url(style.css);` что по сути не имеет смысла
Внесла праки, но почему-то при публикации сайта и просмотре кода они не отображаются

2022-05-04 08:41 UTC, craz3r approved these changes

2022-05-05 11:24 UTC, merged